config = {
    "time_delay": 10,
    "db_config": {
        "db_host": "dhis2_postgres_container",
        "db_name": "dhis2",
        "db_user": "postgres",
        "db_password": "9%4qP7b2H!%J",
        "db_port": "5432"
    },
    "db_columns": {
        "family_planning_monthly":
            {
                "date": "date",
                "facility": "facility",
                "report_name": "report_name",
                "date_created_in_db": "date_created_in_db",
                "frequency": "frequency",
                "report_in_the_system": "report_in_the_system",
                "entered_on_time": "entered_on_time",
                "date_entered_in_system": "date_entered_in_system",
                "days_difference_from_due_date": "days_difference_from_due_date",
                "RHD FP Age Of New Clients On Ceasarean Section 10-14Yrs": "zKmqHtLrUg4_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Ceasarean Section 15-19Yrs": "zKmqHtLrUg4_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Combined oral 10-14Yrs": "T6VHd7wxJxv_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Combined oral 15-19Yrs": "T6VHd7wxJxv_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On IUCD Insertion 10-14Yrs": "eDalBU7XgMg_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On IUCD Insertion 15-19Yrs": "eDalBU7XgMg_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Implants(Implanon) Insertion 10-14Yrs": "bfhwtcBEdp2_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Implants(Implanon) Insertion 15-19Yrs": "bfhwtcBEdp2_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Injectable Depoprovera 10-14Yrs": "SKLzX82U4QW_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Injectable Depoprovera 15-19Yrs": "SKLzX82U4QW_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Interval 10-14Yrs": "LrkIso8fW7M_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Interval 15-19Yrs": "LrkIso8fW7M_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Post Partum 10-14Yrs": "t4TUrKQHyk4_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Post Partum 15-19Yrs": "t4TUrKQHyk4_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Progestrin Only 10-14Yrs": "n9AKjm97zvf_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Progestrin Only 15-19Yrs": "n9AKjm97zvf_F5knYtjFPaJ",
                "RHD FP Contraceptive  Method Ceasarean Section New Clients": "BpJP5VYrNav_SLe9Xo2ScK5",
                "RHD FP Contraceptive Method Combined Oral New Clients": "Fzpjqhpwo9R_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Combined Oral Restarting": "Fzpjqhpwo9R_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Combined Oral Subsequent": "Fzpjqhpwo9R_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Injectable Depoprovera New Clients": "P6Ut87VL6Fe_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Injectable Depoprovera Restarting": "P6Ut87VL6Fe_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Injectable Depoprovera Subsequent": "P6Ut87VL6Fe_JmFPRmJhb7B",
                "RHD FP Contraceptive Method IUCD Insertion New Clients": "DtefmOHJHP9_bnAMGMLaQC7",
                "RHD FP Contraceptive Method IUCD Insertion Restarting": "DtefmOHJHP9_TYaY6QLoEMa",
                "RHD FP Contraceptive Method IUCD Insertion Subsequent": "DtefmOHJHP9_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Post Partum New Clients": "rq54RK1EFVy_SLe9Xo2ScK5",
                "RHD FP Contraceptive Method Progestrin Only New Clients": "Je8fySTIFkr_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Progestrin Only Restarting": "Je8fySTIFkr_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Progestrin Only Subsequent": "Je8fySTIFkr_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera IM New Clients": "mBE1Pn7WjVg_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera IM Restarting": "mBE1Pn7WjVg_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera IM Subsequent": "mBE1Pn7WjVg_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera SC P New Clients": "h5lG3duMzD5_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera SC P Restarting": "h5lG3duMzD5_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera SC P Subsequent": "h5lG3duMzD5_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera SC SI New Clients": "uHCRCXPgObe_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera SC SI Restarting": "uHCRCXPgObe_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera SC SI Subsequent": "uHCRCXPgObe_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Levoplant Insertion New Clients": "hWYkIcjy8EU_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Levoplant Insertion Restarting": "hWYkIcjy8EU_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Levoplant Insertion Subsequent": "hWYkIcjy8EU_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion New Clients": "jCLLHJzxvVS_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion Restarting": "jCLLHJzxvVS_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion Subsequent": "jCLLHJzxvVS_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion New Clients": "oELhEPFX50n_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion Restarting": "oELhEPFX50n_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion Subsequent": "oELhEPFX50n_JmFPRmJhb7B",
            },
    },
    "users": {
        "user": "password",
        "user1": "password"
    }
}
