config = {
    "time_delay": 600,
    "db_config": {
        "db_host": "dhis2_postgres_container",
        "db_name": "dhis2",
        "db_user": "postgres",
        "db_password": "9%4qP7b2H!%J",
        "db_port": "5432"
    },
    "db_columns": {
        "family_planning_monthly":
            {
                "date": "date",
                "facility": "facility",
                "report_name": "report_name",
                "date_created_in_db": "date_created_in_db",
                "frequency": "frequency",
                "report_in_the_system": "report_in_the_system",
                "entered_on_time": "entered_on_time",
                "date_entered_in_system": "date_entered_in_system",
                "days_difference_from_due_date": "days_difference_from_due_date",
                "RHD FP Age Of New Clients On Ceasarean Section 10-14Yrs": "zKmqHtLrUg4_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Ceasarean Section 15-19Yrs": "zKmqHtLrUg4_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Combined oral 10-14Yrs": "T6VHd7wxJxv_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Combined oral 15-19Yrs": "T6VHd7wxJxv_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On IUCD Insertion 10-14Yrs": "eDalBU7XgMg_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On IUCD Insertion 15-19Yrs": "eDalBU7XgMg_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Implants(Implanon) Insertion 10-14Yrs": "bfhwtcBEdp2_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Implants(Implanon) Insertion 15-19Yrs": "bfhwtcBEdp2_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Injectable Depoprovera 10-14Yrs": "SKLzX82U4QW_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Injectable Depoprovera 15-19Yrs": "SKLzX82U4QW_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Interval 10-14Yrs": "LrkIso8fW7M_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Interval 15-19Yrs": "LrkIso8fW7M_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Post Partum 10-14Yrs": "t4TUrKQHyk4_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Post Partum 15-19Yrs": "t4TUrKQHyk4_F5knYtjFPaJ",
                "RHD FP Age Of New Clients On Progestrin Only 10-14Yrs": "n9AKjm97zvf_PMPDwPtyrYG",
                "RHD FP Age Of New Clients On Progestrin Only 15-19Yrs": "n9AKjm97zvf_F5knYtjFPaJ",
                "RHD FP Contraceptive  Method Ceasarean Section New Clients": "BpJP5VYrNav_SLe9Xo2ScK5",
                "RHD FP Contraceptive Method Combined Oral New Clients": "Fzpjqhpwo9R_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Combined Oral Restarting": "Fzpjqhpwo9R_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Combined Oral Subsequent": "Fzpjqhpwo9R_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Injectable Depoprovera New Clients": "P6Ut87VL6Fe_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Injectable Depoprovera Restarting": "P6Ut87VL6Fe_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Injectable Depoprovera Subsequent": "P6Ut87VL6Fe_JmFPRmJhb7B",
                "RHD FP Contraceptive Method IUCD Insertion New Clients": "DtefmOHJHP9_bnAMGMLaQC7",
                "RHD FP Contraceptive Method IUCD Insertion Restarting": "DtefmOHJHP9_TYaY6QLoEMa",
                "RHD FP Contraceptive Method IUCD Insertion Subsequent": "DtefmOHJHP9_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Post Partum New Clients": "rq54RK1EFVy_SLe9Xo2ScK5",
                "RHD FP Contraceptive Method Progestrin Only New Clients": "Je8fySTIFkr_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Progestrin Only Restarting": "Je8fySTIFkr_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Progestrin Only Subsequent": "Je8fySTIFkr_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera IM New Clients": "mBE1Pn7WjVg_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera IM Restarting": "mBE1Pn7WjVg_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera IM Subsequent": "mBE1Pn7WjVg_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera SC P New Clients": "h5lG3duMzD5_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera SC P Restarting": "h5lG3duMzD5_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera SC P Subsequent": "h5lG3duMzD5_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Depoprovera SC SI New Clients": "uHCRCXPgObe_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Depoprovera SC SI Restarting": "uHCRCXPgObe_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Depoprovera SC SI Subsequent": "uHCRCXPgObe_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Levoplant Insertion New Clients": "hWYkIcjy8EU_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Levoplant Insertion Restarting": "hWYkIcjy8EU_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Levoplant Insertion Subsequent": "hWYkIcjy8EU_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion New Clients": "jCLLHJzxvVS_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion Restarting": "jCLLHJzxvVS_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Implants(Implanon) Insertion Subsequent": "jCLLHJzxvVS_JmFPRmJhb7B",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion New Clients": "oELhEPFX50n_bnAMGMLaQC7",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion Restarting": "oELhEPFX50n_TYaY6QLoEMa",
                "RHD FP Contraceptive Method Implants(Jadelle) Insertion Subsequent": "oELhEPFX50n_JmFPRmJhb7B",
            },
        "epi_monthly":
            {
                "date": "date",
                "facility": "facility",
                "report_name": "report_name",
                "date_created_in_db": "date_created_in_db",
                "frequency": "frequency",
                "report_in_the_system": "report_in_the_system",
                "entered_on_time": "entered_on_time",
                "date_entered_in_system": "date_entered_in_system",
                "days_difference_from_due_date": "days_difference_from_due_date",
                "CHD EPI BCG Childhood Vaccination Outreach, Over 1": "s79kWckFPLs_zKLduwqZFnh",
                "CHD EPI BCG Childhood Vaccination Outreach, Under 1": "s79kWckFPLs_ipKITPnwlcP",
                "CHD EPI BCG Childhood Vaccination Static, Over 1": "s79kWckFPLs_r2NJTUrJ2TL",
                "CHD EPI BCG Childhood Vaccination Static, Under 1": "s79kWckFPLs_UHR4d8LgGou",
                "CHD EPI DPT-HepB-Hib1 Childhood Vaccination Outreach, Over 1": "bUpxQhmf8ZK_zKLduwqZFnh",
                "CHD EPI DPT-HepB-Hib1 Childhood Vaccination Outreach, Under 1": "bUpxQhmf8ZK_ipKITPnwlcP",
                "CHD EPI DPT-HepB-Hib1 Childhood Vaccination Static, Over 1": "bUpxQhmf8ZK_r2NJTUrJ2TL",
                "CHD EPI DPT-HepB-Hib1 Childhood Vaccination Static, Under 1": "bUpxQhmf8ZK_UHR4d8LgGou",
                "CHD EPI DPT-HepB-Hib2 Childhood Vaccination Outreach, Over 1": "oVS5H2KNyxb_zKLduwqZFnh",
                "CHD EPI DPT-HepB-Hib2 Childhood Vaccination Outreach, Under 1": "oVS5H2KNyxb_ipKITPnwlcP",
                "CHD EPI DPT-HepB-Hib2 Childhood Vaccination Static, Over 1": "oVS5H2KNyxb_r2NJTUrJ2TL",
                "CHD EPI DPT-HepB-Hib2 Childhood Vaccination Static, Under 1": "oVS5H2KNyxb_UHR4d8LgGou",
                "CHD EPI DPT-HepB-Hib3 Childhood Vaccination Outreach, Over 1": "cq3o6581c85_zKLduwqZFnh",
                "CHD EPI DPT-HepB-Hib3 Childhood Vaccination Outreach, Under 1": "cq3o6581c85_ipKITPnwlcP",
                "CHD EPI DPT-HepB-Hib3 Childhood Vaccination Static, Over 1": "cq3o6581c85_r2NJTUrJ2TL",
                "CHD EPI DPT-HepB-Hib3 Childhood Vaccination Static, Under 1": "cq3o6581c85_UHR4d8LgGou",
                "CHD EPI Fully Immunized children Outreach, Over 1": "NxggSy8gzqo_zKLduwqZFnh",
                "CHD EPI Fully Immunized children Outreach, Under 1": "NxggSy8gzqo_ipKITPnwlcP",
                "CHD EPI Fully Immunized children Static, Over 1": "NxggSy8gzqo_r2NJTUrJ2TL",
                "CHD EPI Fully Immunized children Static, Under 1": "NxggSy8gzqo_UHR4d8LgGou",
                "CHD EPI IPV Childhood Vaccination Outreach, Over 1": "aoEFV2GYFdr_zKLduwqZFnh",
                "CHD EPI IPV Childhood Vaccination Outreach, Under 1": "aoEFV2GYFdr_ipKITPnwlcP",
                "CHD EPI IPV Childhood Vaccination Static, Over 1": "aoEFV2GYFdr_r2NJTUrJ2TL",
                "CHD EPI IPV Childhood Vaccination Static, Under 1": "aoEFV2GYFdr_UHR4d8LgGou",
                "CHD EPI MR1 Childhood Vaccination Outreach, Over 1": "noxYd7tOSon_zKLduwqZFnh",
                "CHD EPI MR1 Childhood Vaccination Outreach, Under 1": "noxYd7tOSon_ipKITPnwlcP",
                "CHD EPI MR1 Childhood Vaccination Static, Over 1": "noxYd7tOSon_r2NJTUrJ2TL",
                "CHD EPI MR1 Childhood Vaccination Static, Under 1": "noxYd7tOSon_UHR4d8LgGou",
                "CHD EPI MR2 Childhood Vaccination Outreach, Over 1": "i78OLuiaUDY_zKLduwqZFnh",
                "CHD EPI MR2 Childhood Vaccination Outreach, Under 1": "i78OLuiaUDY_ipKITPnwlcP",
                "CHD EPI MR2 Childhood Vaccination Static, Over 1": "i78OLuiaUDY_r2NJTUrJ2TL",
                "CHD EPI MR2 Childhood Vaccination Static, Under 1": "i78OLuiaUDY_UHR4d8LgGou",
                "CHD EPI Malaria Vaccine 1 Childhood Vaccination Outreach, Under 1": "a3DjUocUyEa_H5xzz0m9zyd",
                "CHD EPI Malaria Vaccine 1 Childhood Vaccination Static, Under 1": "a3DjUocUyEa_UHR4d8LgGou",
                "CHD EPI Malaria Vaccine 2 Childhood Vaccination Outreach, Under 1": "qcbczRGg4Gm_H5xzz0m9zyd",
                "CHD EPI Malaria Vaccine 2 Childhood Vaccination Static, Under 1": "qcbczRGg4Gm_UHR4d8LgGou",
                "CHD EPI Malaria Vaccine 3 Childhood Vaccination Outreach, Under 1": "MqhI0ToAbRd_H5xzz0m9zyd",
                "CHD EPI Malaria Vaccine 3 Childhood Vaccination Static, Under 1": "MqhI0ToAbRd_UHR4d8LgGou",
                "CHD EPI OPV 0 Childhood Vaccination Outreach, Under 1": "pVdb1wcTMyw_H5xzz0m9zyd",
                "CHD EPI OPV 0 Childhood Vaccination Static, Under 1": "pVdb1wcTMyw_goHo0wV2Gx1",
                "CHD EPI OPV 0 Childhood Vaccination Under 1, Outreach": "pVdb1wcTMyw_G5G3ssAgLIh",
                "CHD EPI OPV 0 Childhood Vaccination Under 1, Static": "pVdb1wcTMyw_JnMvqLEMRHc",
                "CHD EPI OPV1 Childhood Vaccination Outreach, Over 1": "hftsrvq65Ia_zKLduwqZFnh",
                "CHD EPI OPV1 Childhood Vaccination Outreach, Under 1": "hftsrvq65Ia_ipKITPnwlcP",
                "CHD EPI OPV1 Childhood Vaccination Static, Over 1": "hftsrvq65Ia_r2NJTUrJ2TL",
                "CHD EPI OPV1 Childhood Vaccination Static, Under 1": "hftsrvq65Ia_UHR4d8LgGou",
                "CHD EPI OPV2 Childhood Vaccination Outreach, Over 1": "cC69GTz2OSm_zKLduwqZFnh",
                "CHD EPI OPV2 Childhood Vaccination Outreach, Under 1": "cC69GTz2OSm_ipKITPnwlcP",
                "CHD EPI OPV2 Childhood Vaccination Static, Over 1": "cC69GTz2OSm_r2NJTUrJ2TL",
                "CHD EPI OPV2 Childhood Vaccination Static, Under 1": "cC69GTz2OSm_UHR4d8LgGou",
                "CHD EPI OPV3 Childhood Vaccination Outreach, Over 1": "CrELJNRN6Ok_zKLduwqZFnh",
                "CHD EPI OPV3 Childhood Vaccination Outreach, Under 1": "CrELJNRN6Ok_H5xzz0m9zyd",
                "CHD EPI OPV3 Childhood Vaccination Static, Over 1": "CrELJNRN6Ok_r2NJTUrJ2TL",
                "CHD EPI OPV3 Childhood Vaccination Static, Under 1": "CrELJNRN6Ok_UHR4d8LgGou",
                "CHD EPI PCV1 Childhood Vaccination Outreach, Over 1": "TOdUoVRc7n0_zKLduwqZFnh",
                "CHD EPI PCV1 Childhood Vaccination Outreach, Under 1": "TOdUoVRc7n0_ipKITPnwlcP",
                "CHD EPI PCV1 Childhood Vaccination Static, Over 1": "TOdUoVRc7n0_r2NJTUrJ2TL",
                "CHD EPI PCV1 Childhood Vaccination Static, Under 1": "TOdUoVRc7n0_UHR4d8LgGou",
                "CHD EPI PCV2 Childhood Vaccination Outreach, Over 1": "iV9Ijd0qjPU_zKLduwqZFnh",
                "CHD EPI PCV2 Childhood Vaccination Outreach, Under 1": "iV9Ijd0qjPU_ipKITPnwlcP",
                "CHD EPI PCV2 Childhood Vaccination Static, Over 1": "iV9Ijd0qjPU_r2NJTUrJ2TL",
                "CHD EPI PCV2 Childhood Vaccination Static, Under 1": "iV9Ijd0qjPU_UHR4d8LgGou",
                "CHD EPI PCV3 Childhood Vaccination Outreach, Over 1": "luKOKmbulRH_zKLduwqZFnh",
                "CHD EPI PCV3 Childhood Vaccination Outreach, Under 1": "IQFC39nNHPX_ipKITPnwlcP",
                "CHD EPI PCV3 Childhood Vaccination Static, Over 1": "IQFC39nNHPX_r2NJTUrJ2TL",
                "CHD EPI PCV3 Childhood Vaccination Static, Under 1": "IQFC39nNHPX_UHR4d8LgGou",
                "CHD EPI ROTA 1 Childhood Vaccination Outreach, Under 1": "DzCqBNtgw2C_H5xzz0m9zyd",
                "CHD EPI ROTA 1 Childhood Vaccination Static, Under 1": "DzCqBNtgw2C_goHo0wV2Gx1",
                "CHD EPI ROTA 2 Childhood Vaccination Outreach, Under 1": "kBNHszeOCpn_H5xzz0m9zyd",
                "CHD EPI ROTA 2 Childhood Vaccination Static, Under 1": "kBNHszeOCpn_goHo0wV2Gx1",
                "CHD EPI Protection At Birth (PAB) Childhood Vaccination Outreach, Under 1": "ds8EuoyoTUK_H5xzz0m9zyd",
                "CHD EPI Protection At Birth (PAB) Childhood Vaccination Static, Under 1": "ds8EuoyoTUK_goHo0wV2Gx1",
            },
    },
    "users": {
        "apzu_user": "apzu%$2023",
    }
}
